fix script name in some output of annexfmail

diff --git a/bin/annexfmail b/bin/annexfmail
--- a/bin/annexfmail
+++ b/bin/annexfmail
@@ -8,7 +8,7 @@ set -e
 # 1. turn off mbsync for a bit
 
 if pgrep mbsync >/dev/null; then
-    echo "archivemail-ma: mbsync is running so I can't disable it" >&2
+    echo "annexfmail: mbsync is running so I can't disable it" >&2
     exit 1
 fi
 
@@ -27,8 +27,8 @@ suffix=$(date +-%b-%Y | sed 's/\(.*\)/\L\1/')
 # 3. safety check to be sure we don't overwrite anything
 
 if [ -e "$OUTPUT/archive${suffix}.gz" ] || [ -e "$OUTPUT/sent${suffix}.gz" ]; then
-    echo "archivemail-ma: looks like you've already made an archive recently" >&2
-    echo "archivemail-ma: to avoid issues with git-annex, wait until next month"
+    echo "annexfmail: looks like you've already made an archive recently" >&2
+    echo "annexfmail: to avoid issues with git-annex, wait until next month"
     exit 1
 fi
 
