safety check in build for dgit too

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -26,6 +26,13 @@ if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
         else
             arg=""
         fi
+        # safety check before git clean if we're not ignoring
+        if [ ! "$ignore" = "yes" ]; then
+            if git status --porcelain 2>/dev/null | grep -q "^??"; then
+                echo >$2 "abort: untracked files present (to override, try \`buildi')"
+                exit 1
+            fi
+        fi
         dgit $arg build "$@"
         lintian
     else
