try to make doccheckin not fail and stop mr

diff --git a/bin/doccheckin b/bin/doccheckin
--- a/bin/doccheckin
+++ b/bin/doccheckin
@@ -6,10 +6,11 @@ cd ~/doc/
 # blanket commit that merge
 gstatus=$(git status)
 if [[ $gstatus =~ 'You have unmerged paths.' ]]; then
-    exit
+    exit 0
 fi
 
-git add org/*.org playlists/*.m3u emacs-abbrevs emacs-bookmarks mutt-aliases mutt-groups
+# this command should never fail and stop mr
+git add org/*.org playlists/*.m3u emacs-abbrevs emacs-bookmarks mutt-aliases mutt-groups || true
 
 # this command should never fail and stop mr
 git commit -a -m "auto commit on $(hostname -s)" || true
