improve runorraise behaviour for tmux

diff --git a/bin/gnome3-runorraise b/bin/gnome3-runorraise
--- a/bin/gnome3-runorraise
+++ b/bin/gnome3-runorraise
@@ -14,8 +14,17 @@ case $1 in
         wmctrl -a "spw@ma" || urxvtma &
         ;;
     term)
-        wmctrl -a "Local tmux" || urxvttmux &
-        sleep 0.2
-        wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
+        currwin=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2)
+        tmuxtitle="terms"
+        # if we're already looking at tmux, maximise it
+        if [ "$currwin" = "$tmuxtitle" ]; then
+            sleep 0.2
+            wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
+        else
+            # We're not looking at tmux.  Try to raise it.  If that fails, launch it.b
+            if ! wmctrl -a "$tmuxtitle"; then
+                urxvt ++iso14755 ++iso14755_52 -title "$tmuxtitle" -e /bin/sh -c 'tmux attach' &
+            fi
+        fi
         ;;
 esac
